const theme = {
  colors: {
    primaryTextColor: "#FFFFFF",
    backgroundColor: "#070724",
    BrightGray: "#38384F",
    Earth: "#6D2ED5",
    Waterloo: "#838391",
    Mercury: "#419EBB",
    Venus: "#EDA249",
    PurpleHeart: "#6f2ed6",
    Mars: "#D14C32",
    Jupiter: "#D83A34",
    Saturn: "#CD5120",
    Uranus: "#1ec2a4",
    Neptune: "#2d68f0",
  },
  typograpthy: {
    NavigationLink: {
      FontSize: "11px",
      FontWeight: 700,
      lineHeight: "25px",
      letterSpacing: "1px",
      textTransform: "uppercase",
      fontFamily: "'League Spartan', sans-serif",
    },
    Logo: {
      FontSize: "28px",
      FontWeight: 400,
      lineHeight: "normal",
      letterSpacing: "-1.05px",
      textTransform: "uppercase",
      fontFamily: "'Antonio', sans-serif",
    },
    PlanetTitle: {
      FontSize: "80px",
      FontWeight: 400,
      lineHeight: "normal",
      textTransform: "uppercase",
      fontFamily: "'Antonio', sans-serif",
    },
    Paragraph: {
      FontSize: "14px",
      FontWeight: 400,
      lineHeight: "25px",
      textTransform: "uppercase",
      fontFamily: "'League Spartan', sans-serif",
    },
    PlanetContentTopic: {
      FontSize: "12px",
      FontWeight: 700,
      lineHeight: "25px",
      textTransform: "uppercase",
      fontFamily: "'League Spartan', sans-serif",
    },
    GeneralInformationBoxes: {
      title: {
        color: "rgb(256,256,256,0.6)",
        fontFamily: "'League Spartan', sans-serif",
        fontSize: "11px",
        fontStyle: "normal",
        fontWeight: 700,
        lineHeight: "25px",
        letterSpacing: "1px",
        textTransform: "uppercase",
      },
      content: {
        fontFamily: "'Antonio', sans-serif",
        fontSize: "40px",
        fontStyle: "normal",
        fontWeight: 400,
        lineHeight: "normal",
        letterSpacing: "-1.5px",
        textTransform: "uppercase",
      },
    },
  },
};
export default theme;
